myApp.controller('NewsCtrl',['$scope','$rootScope', function($scope,$rootScope){
	$scope.today = function(element) {
		return element.day == $rootScope.currentDay ? true : false;
	};
	$rootScope.news = [
		{day:1, time: 100, text:'18 Suicides in the last year. Just what is going wrong in FaxLan?'},
		{day:1, time: 100, text:'Black Subsidiaries releases the "Oqular" - The world\'s first consumer synthetic implant.'},
		{day:1, time: 200, text:'Ancient desktop computer believed to belong to YouTube celebrity sold in novelty online auction.'},
		{day:1, time: 200, text:'Is the Oqular going to be the massive cultural change it\'s hyped to be? We\'re not so sure'},
		{day:1, time: 200, text:'North Korea threatens nuclear war, South Korea threatens zerg rush'},
		{day:1, time: 200, text:'The best programming tools: Never use a keyboard again!'},
		{day:1, time: 200, text:'The Truth About Web 3.0 - A complete explanation, from concepts hardware'},
		{day:1, time: 200, text:'This Is How The War On Drugs Ends: Not with a bang, but with the flick of a switch'},
		{day:1, time: 200, text:'Why Linux has been better for 500 years, but still no one\'s using it.'},

		{day:2, time: 100, text:'As cybernetic implants become commonplace, legislators scramble to plug leaks in a legal system failing to cope with technology'},
		{day:2, time: 100, text:'Conditions in factories that produces the Oqular are worse than ever imagined'},
		{day:2, time: 100, text:'NASA: "The next space race isn\'t for planets, it\'s for galaxies"'},
		{day:2, time: 200, text:'A cheap method for creating hydrogen for fuel cells'},
		{day:2, time: 200, text:'Amazingly Creative Japanese Packaging'},
		{day:2, time: 200, text:'Centuries old dilbert comic still strangely relevant'},
		{day:2, time: 200, text:'Japanese company claims to have made a fully autonomous robot for under $1000'},
		{day:2, time: 200, text:'Machine learning methods are being used everywhere, from smart-coms to toasters'},
		{day:2, time: 200, text:'The promise of the cloud, and why it never rained'},
		{day:2, time: 200, text:'What your smart-com does while you wait for it to start'},

		{day:3, time: 100, text:'Cybernetic watchlist passes. Police now have the right to scan your recorded memories at checkpoints nation-wide.'},
		{day:3, time: 100, text:'Right now, a "cybernetic terrorism watchlist" bill is being presented to the government. If it passes, we all lose.'},
		{day:3, time: 200, text:'Climate deemed "too controversial a topic" for discussion at NATIONAL SCIENCE CONVENTION'},
		{day:3, time: 200, text:'NY Standard: "It\'s surreal how disconnected our President is from reality"'},
		{day:3, time: 200, text:'The science behind how you should be sitting at work'},
		{day:3, time: 200, text:'The strangest software bug in recorded history'},

		{day:4, time: 100, text:'Child with cybernetic limbs forced to remove them in front of class by asshole cop.'},
		{day:4, time: 100, text:'In addition to body scanners at all major airports, you can now expect them at train stations.'},
		{day:4, time: 200, text:'Black Friday sales may be outlawed after another trampling last week'},
		{day:4, time: 200, text:'Legal Oqular download vs Pirated Copy'},
		{day:4, time: 200, text:'Quantum mechanics made simple (5th grade and up)'},
		{day:4, time: 200, text:'Scandal breaks out in east coast navy base'},
		{day:4, time: 200, text:'Man robs bank, explains to teller "It\'s a science experiment".'},

		{day:5, time: 100, text:'Q-bots set to replace minimum wage workers in stores across the country'},
		{day:5, time: 100, text:'With all the pro-democracy protests going on in the world, why don\'t we stage our own day of protest against the expansion of the "cybernetic terrorism" act?'},
		{day:5, time: 200, text:'A look back at the Y2K phenomenon. What caused it? Why didn\'t we stop it?'},
		{day:5, time: 200, text:'Check out some of these comments from an ancient Ruby on Rails application'},
		{day:5, time: 200, text:'Flash mob fills park with 100\'s of statue impersonators!'},
		{day:5, time: 200, text:'Spectacular photo of lightning hitting an airplane'},
		{day:5, time: 200, text:'The legal limitations in xOS software may be more than you bargained for'},

		{day:6, time: 100, text:'Cybernetic rights protests occur world wide as "pluggers" demand equal treatment and consumer protections.'},
		{day:6, time: 100, text:'Man with over 80 implants is officially more machine than man'},
		{day:6, time: 100, text:'Q-Mart pays itself rent, gets large tax breaks'},
		{day:6, time: 100, text:'What\'s your favourite one-liner joke?'},
		{day:6, time: 200, text:'Astronauts had to go through US Customs to return from Moon '},
		{day:6, time: 200, text:'Computers are in everything: Exploring the death of the geek'},
		{day:6, time: 200, text:'Sexbots are starting to become a little TOO commonplace near my work [NSFW]'},
		{day:6, time: 200, text:'The numbers and science behind online dating'},

		{day:7, time: 100, text:'"Advances in synthetic AI technology are now moving faster than anything we ever imagined" - Black Subsidiaries engineer'},
		{day:7, time: 100, text:'"Checklist" stops will be less frequent - "random" checks will still occur, will no longer scan data.'},
		{day:7, time: 100, text:'Cheese sandwich looks exactly like... wait for it...'},
		{day:7, time: 200, text:'What modern practice do you think is surprisingly out-dated and can\'t wait to see improved?'},
		{day:7, time: 200, text:'Dear Skimmit, Please don\'t take me away from what i was looking at when i log in.'},
		{day:7, time: 200, text:'Gravity - just a theory'},
		{day:7, time: 200, text:'Man falls off sofa while laughing, downstairs neighbour thought he collapsed and called the police. Police shoot him no less than 40 times.'},
		{day:7, time: 200, text:'Mexico accuses Synthetic minority group of threatening to sabotage Olympics'},
		{day:7, time: 200, text:'Our country\'s presidents, and the books they tried to ban'},
		{day:7, time: 200, text:'The deep philosophical differences between Q-COMPLEX and Q-SIMPLE.'},

		{day:8, time: 100, text:'Advanced synthetics seek equal rights as "non-human persons"'},
		{day:8, time: 100, text:'Kindergarten teacher quits job to make six figures Querking for a living'},
		{day:8, time: 100, text:'One of these two men is synthetic. One is human. Can you tell which is which?'},
		{day:8, time: 200, text:'Ancient phonebooth from the 1960\'s finally reinstalled at its original site'},
		{day:8, time: 200, text:'Possibly the most insane thing you\'ll see today: a flash-based website from the late 1990\'s (You\'ll need an emulator)'},
		{day:8, time: 200, text:'Put the Gangs out of Business: Legalize Synthetic Drugs'},
		{day:8, time: 200, text:'School used student Oqulars to spy on them at school and home - the Oqulars issued to high-school students can be covertly activated by the schools\' administrators, who have used this facility to spy on students and even their families.'},

		{day:9, time: 100, text:'Introduction to Abstract-Concept-Oriented Programming'},
		{day:9, time: 200, text:'Man steals zeppelin, tells pilot "It\'s a science experiment". Blimp is never seen again.'},
		{day:9, time: 100, text:'Protests erupt into riots as Synthetic Rights bill vetoed by government council'},
		{day:9, time: 100, text:'Zero fucks were given by this guy in class today'},
		{day:9, time: 200, text:'Black Subsidiaries hit with massive antitrust fine after documents leaked during office massacre.'},
		{day:9, time: 200, text:'Bottled water? Really? The wastefulness of the 20th century'},
		{day:9, time: 200, text:'Conspiracy theory proven true after 40 years when original hoaxer comes forward.'},
		{day:9, time: 200, text:'Despite the Information Age, our college freshmen are morons'},
		{day:9, time: 200, text:'With the growing inconveniences of the online marketspace, shoppers are going the one place no one expected: Outside'},
		{day:9, time: 200, text:'Woman with motor neurone disease becomes first human being to transition completely to a synthetic body.'},

		{day:10, time: 100, text:'Now that someone\'s gone from human to synthetic, could you do the reverse?'},
		{day:10, time: 100, text:'Smooth...'},
		{day:10, time: 100, text:'Synthetics granted not just "non-human person" rights, but full human rights!'},
		{day:10, time: 100, text:'What\'s something stupid people used to do in the 2010\'s to be "cool"?'},
		{day:10, time: 200, text:'"Unparalleled character customization...blows everything else out of the water." Actually just a boob-size slider'},
		{day:10, time: 200, text:'Angry disenfranchised men start an underground club, create propaganda despite unclear leaders, destructive operations because of ethics.'},
		{day:10, time: 200, text:'Modern Warfare 27 - New Multiplayer footage. 3/2/44'},
		{day:10, time: 200, text:'Software developers: Stop trying to sneak toolbars into your installer packages. We didn\'t want them last century, and we don\'t want them now.'},
		{day:10, time: 200, text:'The science behind cat videos: without being able to match faces to names, net users end up far more empathetic to animals than other humans.'},

		{day:11, time: 100, text:'A guide for pairing lubricant and inorganic compounds'},
		{day:11, time: 100, text:'Skimmit has been purchased by Q-Media!'},
		{day:11, time: 100, text:'Ubuntu linux finally reaches Zealous Zebra.'},
		{day:11, time: 100, text:'What\'s the stupidest thing to ever make the front page of Skimmit?'},
		{day:11, time: 100, text:'Winter is coming'},
		{day:11, time: 200, text:'Man hijacks train, tells conductor "It\'s a science experiment". Completely vanishes before cops arrive.'},
		{day:11, time: 200, text:'There are no stupid questions, except this one.'},
		{day:11, time: 200, text:'This is how my little cousin plays Oqular games'},
		{day:11, time: 200, text:'What\'s your favourite one-liner joke?'},

		{day:12, time: 100, text:'CDC confirms that synthetic virus has been diagnosed in human (with implants) For the first time.'},
		{day:12, time: 100, text:'My curious kitten'},
		{day:12, time: 100, text:'Who wore it better?'},
		{day:12, time: 200, text:'Found this little guy while mowing'},
		{day:12, time: 200, text:'So I found this in the attic...'},
		{day:12, time: 200, text:'Urge to kill... rising...'},
		{day:12, time: 200, text:'What happens when a thunderstorm hits'},
		{day:12, time: 200, text:'Winter is coming'},

		{day:13, time: 100, text:'Excellent post'},
		{day:13, time: 100, text:'I Threw My Oqular in the Air 10 Times and Hoped For the Best'},
		{day:13, time: 100, text:'Like a pro'},
		{day:13, time: 100, text:'My friend was in a pet shop and saw these'},
		{day:13, time: 100, text:'My right elbow has never been touched by my right hand.'},
		{day:13, time: 100, text:'So cute, it almost hurts to look at.'},
		{day:13, time: 100, text:'This photo was a great way to start my morning.'},
		{day:13, time: 100, text:'Unimpressed cat'},
		{day:13, time: 100, text:'My dog and his best friends: they\'re all stuffed toys'},
	];
}])